version: '3'
services:
  backup-service:
    build: .
    platform: linux/amd64
    volumes:
      - /path/to/local/folders:/backup/source
      - ./config:/app/config
    environment:
      - TZ=UTC
    restart: unless-stopped 