services:
  backup-service:
    image: ahaltindis/nas-backup-tool:latest
    # build: .  # To directly build from source
    platform: linux/amd64
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN  # mount
      - DAC_READ_SEARCH  # cifs/sambda specific
      - NET_ADMIN  # for WOL broadcast
    network_mode: "host"  # Required for WOL broadcast
    security_opt:
      - apparmor:unconfined  # Required for mount
    volumes:
      # Mount example source directories (customize these)
      - /home/user/documents:/backup/source/documents:ro
      - /home/user/photos:/backup/source/photos:ro
      # Mount config file and credentials
      - ./backup_config.yaml:/app/config.yaml:ro
      - ./nas_credentials:/etc/nas_credentials:ro
    environment:
      - TZ=UTC
      - CONFIG_FILE=/app/config.yaml
