nas:
  mac_address: "00:11:22:33:44:55"  # NAS MAC address for Wake-on-LAN
  ip: "192.168.1.100"
  username: "admin"
  shutdown_command: "shutdown -h now"
  mount:
    remote_path: "volume1"  # NAS share path
    local_path: "/mnt/nas-backup"   # Local mount point
    type: "cifs"                    # Mount type (nfs or cifs)
    options: "vers=3"
    cifs:
      credentials: "/etc/nas_credentials"  # Samba credentials file

backup:
  directories:
    - source: "/home/user/documents"
      destination: "/mnt/nas-backup/documents"
    - source: "/home/user/photos"
      destination: "/mnt/nas-backup/photos"
  frequency: "daily"  # daily, weekly, monthly

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender: "your-email@gmail.com"
  password: "your-app-password" # Gmail App Password
  recipient: "your-personal@gmail.com"

